# config_CNN3D.yaml
# Configuration file for the grid-based CNN3D model

project_setup:
  experiment_name: "SPEI_CNN3D_Global_Run"
  target_variable: "spei"
  random_seed: 42

data:
  raw_data_path: "data/full.csv"
  time_column: "time"
  lat_column: "lat"
  lon_column: "lon"
  # List of all features that will be converted into grid channels
  features_to_grid: [
      'spei', 'tmp', 'dtr', 'cld', 'tmx', 
      'tmn', 'wet', 'vap', 'soi', 
      'dmi', 'pdo', 'nino4', 
      'nino34', 'nino3', 'pre', 'pet'
    ]
  # Dates for splitting the final gridded tensor
  train_end_date: "2017-12-31"
  validation_end_date: "2020-12-31"

gridding:
  # This tells the grid_utils.py script the native resolution of your data
  # The final grid dimensions (height and width) will be calculated from this.
  fixed_step: 0.5 

sequence_params:
  # These define the "window" for the CNN3D model
  n_steps_in: 12      # How many past months (time depth) to use as input
  n_steps_out: 1      # How many months to predict into the future

cnn3d_params:
  batch_size: 16      # Batch size for training. Keep this smaller for 3D models due to memory usage.

  trainer:
    max_epochs: 300
    patience_for_early_stopping: 5
    accelerator: "auto"
    enable_progress_bar: True
  
  tuning:
    n_trials: 1      # Number of Optuna trials to run for hyperparameter search
    learning_rate: {low: 1.0e-6, high: 1.0e-5, log: True}
    # Search space for the CNN architecture
    n_conv_layers: {low: 2, high: 4}
    out_channels_power: {low: 4, high: 6} # Num filters (2^4=16 to 2^6=64)
    # Kernel size for each dimension (Depth, Height, Width)
    kernel_size_d: {choices: [3, 5]} # Time dimension kernel
    kernel_size_h: {choices: [3, 5]} # Height dimension kernel
    kernel_size_w: {choices: [3, 5]} # Width dimension kernel
        
paths:
  models_base_dir: "models_saved" 

results:
  output_base_dir: "run_outputs" 
  metrics_filename: "global_cnn3d_metrics.json"
  predictions_filename: "global_cnn3d_full_predictions.csv"
  config_filename: "config_used_for_run.yaml"